---
ID: "c52ea683-f742-422e-b20a-295ede29f8eb"
Parent: "b83f10f1-6f84-49e2-a807-856b6ff6c10a"
Template: "b83f10f1-6f84-49e2-a807-856b6ff6c10a"
Path: /sitecore/templates/Feature/Constellation/Navigation/Page Navigation Title/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171129T212938Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rcabral
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rcabral
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "917d7b6e-0d20-4c18-a3d0-47bdab945da1"
    - ID: "a8fad4b5-f582-4b63-9031-8fa8ea8b6d06"
      Hint: navigationTitle
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rcabral
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20171129T212945Z
